force-app/main/default/objects/Case/fields/Is_Awaiting_Customer__c.field-meta.xml
<CustomField>
    <fullName>Is_Awaiting_Customer__c</fullName>
    <formula>BLANKVALUE(Last_Agent2Customer__c, CreatedDate ) &gt;
BLANKVALUE(Last_Customer2Agent__c, CreatedDate )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Awaiting Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Is_Customer_Waiting__c.field-meta.xml
<CustomField>
    <fullName>Is_Customer_Waiting__c</fullName>
    <formula>BLANKVALUE( Last_Customer2Agent__c , CreatedDate ) &gt; BLANKVALUE( Last_Agent2Customer__c , CreatedDate )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Customer Waiting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Agent2Customer__c.field-meta.xml
<CustomField>
    <fullName>Last_Agent2Customer__c</fullName>
    <label>Last Agent to Customer</label>
    <summarizedField>Case_Interaction__c.Interaction_Datetime__c</summarizedField>
    <summaryFilterItems>
        <field>Case_Interaction__c.Trackable__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Case_Interaction__c.Sender__c</field>
        <operation>equals</operation>
        <value>AGENT</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Case_Interaction__c.Recipient__c</field>
        <operation>equals</operation>
        <value>CUSTOMER</value>
    </summaryFilterItems>
    <summaryForeignKey>Case_Interaction__c.Case__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Customer2Agent__c.field-meta.xml
<CustomField>
    <fullName>Last_Customer2Agent__c</fullName>
    <label>Last Customer to Agent</label>
    <summarizedField>Case_Interaction__c.Interaction_Datetime__c</summarizedField>
    <summaryFilterItems>
        <field>Case_Interaction__c.Trackable__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Case_Interaction__c.Sender__c</field>
        <operation>equals</operation>
        <value>CUSTOMER</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Case_Interaction__c.Recipient__c</field>
        <operation>equals</operation>
        <value>AGENT</value>
    </summaryFilterItems>
    <summaryForeignKey>Case_Interaction__c.Case__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case_Interaction__c/Case_Interaction__c.object-meta.xml
<CustomObject>
    <label>Case Interaction</label>
    <nameField>
        <displayFormat>CI{000000}</displayFormat>
        <label>Case Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Interaction__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Interactions</relationshipLabel>
    <relationshipName>Case_Interactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Interaction__c/fields/Interaction_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Datetime__c</fullName>
    <label>Interaction Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Interaction__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <label>Recipient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Interaction_Parties</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Interaction__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <label>Sender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Interaction_Parties</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Interaction__c/fields/Trackable__c.field-meta.xml
<CustomField>
    <fullName>Trackable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trackable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Interaction_Parties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AGENT</fullName>
    </customValue>
    <customValue>
        <fullName>INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>CUSTOMER</fullName>
    </customValue>
    <customValue>
        <fullName>PARTNER</fullName>
    </customValue>
    <masterLabel>Interaction Parties</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CaseMilestonesTest.cls
@IsTest
private class CaseMilestonesTest {
    @IsTest
    static void createNoCriteriaMilestones() {
        Account testAccount = new Account(
            Name = 'test');
        insert testAccount;

        Entitlement testEntitlement = new Entitlement(
            AccountId = testAccount.Id,
            Name = 'test');
        insert testEntitlement;

        Case testCase = new Case(
            Priority = 'Medium',
            Origin = 'Email',
            EntitlementId = testEntitlement.Id,
            AccountId = testAccount.Id);

        Test.startTest();
        insert testCase;
        Test.stopTest();

        // Doing this with the UI, some milestones get created, namely 'Resolution' and 'Close Case'
        List<CaseMilestone> milestones = [SELECT Id FROM CaseMilestone WHERE CaseId = :testCase.Id];
        System.assertNotEquals(0, milestones.size(), 'size of milestones');
    }
    @IsTest
    static void createMilestonesWithCriteria() {
        Account testAccount = new Account(
            Name = 'test');
        insert testAccount;

        Entitlement testEntitlement = new Entitlement(
            AccountId = testAccount.Id,
            Name = 'test');
        insert testEntitlement;

        Case testCase = new Case(
            Priority = 'Medium',
            Origin = 'Email',
            EntitlementId = testEntitlement.Id,
            AccountId = testAccount.Id);
        insert testCase;
        Test.setCreatedDate(testCase.Id, System.now().addHours(-1));

        Test.startTest();
        insert new Case_Interaction__c(
            Case__c = testCase.Id,
            Trackable__c = true,
            Interaction_Datetime__c = System.now().addMinutes(-5),
            Sender__c = 'CUSTOMER',
            Recipient__c = 'AGENT');
        Test.stopTest();

        Case checkCase = [SELECT OwnerId, Is_Awaiting_Customer__c, Is_Customer_Waiting__c, Last_Customer2Agent__c, Last_Agent2Customer__c FROM Case WHERE Id = :testCase.Id];
        System.assert(checkCase.Is_Customer_Waiting__c, 'customer should be waiting'); // when this is true, the SLA process should create a milestone called 'Respond to Customer'. This works as expected through UI.

        List<CaseMilestone> milestones = [SELECT Id FROM CaseMilestone WHERE CaseId = :testCase.Id AND MilestoneType.Name = 'Respond to Customer'];
        System.assertNotEquals(0, milestones.size(), 'size of milestones');
    }
}